version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - wget http://www-eu.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz
      - tar -xzf apache-maven-3.5.4-bin.tar.gz
      - ln -s apache-maven-3.5.4 maven

  post_build:
    commands:
      - mvn package
      - mv target/Project1Servlet-0.0.1-SNAPSHOT.war ROOT.war
artifacts:
  files:
    - ROOT.war